layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: nasreddine.bacali
  linkedin: bacali
  instagram: _bacali
  website: https://nasreddinebacali.info
  hackerrank: bacali
  keybase: bacali_
  # mastodon: your_username
  medium: bacali
  stackoverflow: 9751650
  # telegram: your_username
  twitter: _bacali
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
  
  - name: NPM
    web_url: https://github.com/topics/npm
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/npm/npm.png
  
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Algorithm
    web_url: https://github.com/topics/algorithm
